/**
 * Creates the schema in the connected Supabase Postgres database from the
 * Sequelize models, and captures the DDL into supabase/migrations/ so the
 * Supabase CLI (`supabase db push`) can replay it on other environments.
 *
 * The capture runs against a throwaway scratch database (created and dropped
 * here) in a child process, so re-running this script always produces a
 * complete file even when the live schema already exists. The captured SQL is
 * then replayed into a second scratch database as a syntax/semantic check.
 *
 * Usage: node scripts/migrate.js
 */
import 'dotenv/config';
import { mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { Sequelize, QueryTypes } from 'sequelize';

import { sequelize, dbUrl } from '../server/config/db.js';

const MAIN_URL = dbUrl;
if (!MAIN_URL) {
  console.error('[migrate] no database URL set (SUPABASE_DB_URL / POOLER_URL / DATABASE_URL)');
  process.exit(1);
}
const scratchUrl = (name) => MAIN_URL.replace(/\/([^/?]+)(\?|$)/, `/${name}$2`);

const isNoise = (sql) =>
  sql.length === 0 ||
  /^(BEGIN|COMMIT|ROLLBACK|SAVEPOINT|RELEASE|SET |SELECT |SHOW |CREATE DATABASE|DROP DATABASE)/i.test(sql);

const admin = new Sequelize(MAIN_URL, {
  dialect: 'postgres',
  logging: false,
  dialectOptions: { ssl: { require: true, rejectUnauthorized: false } },
});

const withScratch = async (name, fn) => {
  // Supabase's Supavisor pooler keeps a warm backend per database and
  // reconnects instantly when it is terminated, so plain DROP DATABASE fails
  // with "is being accessed by other users". WITH (FORCE) kills remaining
  // backends and drops in one server-side statement.
  await admin.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`);
  await admin.query(`CREATE DATABASE ${name}`);
  try {
    return await fn(scratchUrl(name));
  } finally {
    await admin.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`);
  }
};

try {
  // 1. Apply the schema to the live database (models are bound to the config
  //    connection, so this is the one sync that talks to Supabase's main DB).
  await sequelize.authenticate();
  console.log('Applying schema to the live database...');
  await sequelize.sync({ force: false });
  const tables = await sequelize.query(
    `SELECT table_name AS name FROM information_schema.tables WHERE table_schema='public' ORDER BY table_name`,
    { type: QueryTypes.SELECT }
  );
  console.log('Tables now present:');
  tables.forEach((t) => console.log(' -', (t as any).name));
  await sequelize.close();

  // 2. Capture the full DDL by syncing the models into a scratch database from
  //    a child process (fresh module graph -> models bind to the scratch URL).
  const captured = await withScratch('eduvia_ddl_capture', async (url) => {
    const child = spawnSync(
      process.execPath,
      ['--import', 'tsx', path.join(path.dirname(fileURLToPath(import.meta.url)), 'capture-ddl.ts')],
      {
        env: { ...process.env, SUPABASE_DB_URL: url },
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024,
      }
    );
    if (child.status !== 0) {
      throw new Error(`capture-ddl failed: ${child.stderr || child.stdout}`);
    }
    return JSON.parse(child.stdout);
  });

  // `CREATE INDEX IF NOT EXISTS` keeps the file replayable on an environment
  // where migrate.js already applied the schema (as `supabase db push` would).
  const ddl = captured
    .map((sql) => sql.trim())
    .filter((sql) => !isNoise(sql))
    .join(';\n\n')
    .replace(/CREATE INDEX /g, 'CREATE INDEX IF NOT EXISTS ');

  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const migrationsDir = path.resolve(__dirname, '../supabase/migrations');
  mkdirSync(migrationsDir, { recursive: true });
  for (const f of readdirSync(migrationsDir)) {
    if (f.endsWith('_init_schema.sql')) unlinkSync(path.join(migrationsDir, f));
  }
  const ts = new Date().toISOString().replace(/[-T:.Z]/g, '').slice(0, 14);
  const file = path.join(migrationsDir, `${ts}_init_schema.sql`);
  const header =
    '-- Generated by scripts/migrate.ts - schema for the Eduvia backend.\n' +
    '-- Replayed by `supabase db push` on other Supabase environments.\n\n';
  const content = `${header}${ddl};\n`;
  writeFileSync(file, content);

  // 3. Validate: replay the captured file into a second scratch database.
  console.log('Validating captured DDL against a fresh scratch database...');
  await withScratch('eduvia_ddl_validate', async (url) => {
    const validate = new Sequelize(url, {
      dialect: 'postgres',
      logging: false,
      dialectOptions: { ssl: { require: true, rejectUnauthorized: false } },
    });
    try {
      await validate.query(content);
      const rows = await validate.query(
        `SELECT table_name AS name FROM information_schema.tables WHERE table_schema='public' ORDER BY table_name`,
        { type: QueryTypes.SELECT }
      );
      console.log(`Replay OK - ${rows.length} tables created from the file.`);
      if (rows.length < 20) throw new Error('replay produced too few tables');
    } finally {
      await validate.close();
    }
  });

  await admin.close();
  console.log(`DDL written to ${file}`);
  process.exit(0);
} catch (err) {
  console.error('Migration failed:', err.message);
  if (err.parent) console.error('cause:', err.parent.message);
  await admin.close().catch(() => {});
  process.exit(1);
}
