-- Generated by scripts/migrate.ts - schema for the Eduvia backend.
-- Replayed by `supabase db push` on other Supabase environments.

DROP TABLE IF EXISTS "testimonials" CASCADE;;

DROP TABLE IF EXISTS "teammembers" CASCADE;;

DROP TABLE IF EXISTS "successstories" CASCADE;;

DROP TABLE IF EXISTS "sitesettings" CASCADE;;

DROP TABLE IF EXISTS "services" CASCADE;;

DROP TABLE IF EXISTS "pageseos" CASCADE;;

DROP TABLE IF EXISTS "faqs" CASCADE;;

DROP TABLE IF EXISTS "contactmessages" CASCADE;;

DROP TABLE IF EXISTS "media" CASCADE;;

DROP TABLE IF EXISTS "inquiries" CASCADE;;

DROP TABLE IF EXISTS "applications" CASCADE;;

DROP TABLE IF EXISTS "scholarships" CASCADE;;

DROP TABLE IF EXISTS "destination_related_blogs" CASCADE;;

DROP TABLE IF EXISTS "destinations" CASCADE;;

DROP TABLE IF EXISTS "course_universities" CASCADE;;

DROP TABLE IF EXISTS "courses" CASCADE;;

DROP TABLE IF EXISTS "students" CASCADE;;

DROP TABLE IF EXISTS "blog_related_posts" CASCADE;;

DROP TABLE IF EXISTS "blogs" CASCADE;;

DROP TABLE IF EXISTS "universities" CASCADE;;

DROP TABLE IF EXISTS "admins" CASCADE;;

DROP TABLE IF EXISTS "admins" CASCADE;;

DROP TABLE IF EXISTS "universities" CASCADE;;

DROP TABLE IF EXISTS "blogs" CASCADE;;

DROP TABLE IF EXISTS "blog_related_posts" CASCADE;;

DROP TABLE IF EXISTS "students" CASCADE;;

DROP TABLE IF EXISTS "courses" CASCADE;;

DROP TABLE IF EXISTS "course_universities" CASCADE;;

DROP TABLE IF EXISTS "destinations" CASCADE;;

DROP TABLE IF EXISTS "destination_related_blogs" CASCADE;;

DROP TABLE IF EXISTS "scholarships" CASCADE;;

DROP TABLE IF EXISTS "applications" CASCADE;;

DROP TABLE IF EXISTS "inquiries" CASCADE;;

DROP TABLE IF EXISTS "media" CASCADE;;

DROP TABLE IF EXISTS "contactmessages" CASCADE;;

DROP TABLE IF EXISTS "faqs" CASCADE;;

DROP TABLE IF EXISTS "pageseos" CASCADE;;

DROP TABLE IF EXISTS "services" CASCADE;;

DROP TABLE IF EXISTS "sitesettings" CASCADE;;

DROP TABLE IF EXISTS "successstories" CASCADE;;

DROP TABLE IF EXISTS "teammembers" CASCADE;;

DROP TABLE IF EXISTS "testimonials" CASCADE;;

DROP TABLE IF EXISTS "admins" CASCADE;;

CREATE TABLE IF NOT EXISTS "admins" ("id" UUID , "name" VARCHAR(100) NOT NULL, "email" VARCHAR(255) NOT NULL UNIQUE, "password" VARCHAR(255) NOT NULL, "role" VARCHAR(255) NOT NULL DEFAULT 'admin', "avatar" VARCHAR(255) NOT NULL DEFAULT '', "is_active" BOOLEAN NOT NULL DEFAULT true, "last_login" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

DROP TABLE IF EXISTS "universities" CASCADE;;

CREATE TABLE IF NOT EXISTS "universities" ("id" UUID , "name" VARCHAR(255) NOT NULL UNIQUE, "slug" VARCHAR(255) UNIQUE, "country" VARCHAR(255) NOT NULL, "city" VARCHAR(255), "logo" VARCHAR(255) NOT NULL DEFAULT '', "cover_image" VARCHAR(255) NOT NULL DEFAULT '', "description" TEXT NOT NULL DEFAULT '', "short_description" VARCHAR(300), "website" VARCHAR(255), "ranking" VARCHAR(255), "founded" VARCHAR(255), "type" VARCHAR(255) NOT NULL DEFAULT 'public', "programs" JSONB NOT NULL, "scholarships" JSONB NOT NULL, "entry_requirements" TEXT, "tuition_range" VARCHAR(255), "features" JSONB NOT NULL, "is_featured" BOOLEAN NOT NULL DEFAULT false, "is_active" BOOLEAN NOT NULL DEFAULT true, "seo" JSONB NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "universities_country" ON "universities" ("country");

CREATE INDEX IF NOT EXISTS "universities_is_featured" ON "universities" ("is_featured");

CREATE INDEX IF NOT EXISTS "universities_slug" ON "universities" ("slug");

CREATE INDEX IF NOT EXISTS "universities_created_at" ON "universities" ("created_at");

DROP TABLE IF EXISTS "blogs" CASCADE;;

CREATE TABLE IF NOT EXISTS "blogs" ("id" UUID , "title" VARCHAR(255) NOT NULL, "slug" VARCHAR(255) UNIQUE, "author" VARCHAR(255) NOT NULL DEFAULT 'Eduvia Team', "content" TEXT NOT NULL, "excerpt" VARCHAR(500), "featured_image" VARCHAR(255) NOT NULL DEFAULT '', "category" VARCHAR(255), "tags" JSONB NOT NULL, "read_time" INTEGER NOT NULL DEFAULT 5, "is_published" BOOLEAN NOT NULL DEFAULT false, "published_at" TIMESTAMP WITH TIME ZONE, "seo" JSONB NOT NULL, "views" INTEGER NOT NULL DEFAULT 0, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "blogs_category" ON "blogs" ("category");

CREATE INDEX IF NOT EXISTS "blogs_is_published" ON "blogs" ("is_published");

CREATE INDEX IF NOT EXISTS "blogs_created_at" ON "blogs" ("created_at");

CREATE INDEX IF NOT EXISTS "blogs_slug" ON "blogs" ("slug");

CREATE INDEX IF NOT EXISTS "blogs_tags" ON "blogs" USING gin ("tags");

DROP TABLE IF EXISTS "blog_related_posts" CASCADE;;

CREATE TABLE IF NOT EXISTS "blog_related_posts" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "blog_id" UUID  REFERENCES "blogs" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "related_post_id" UUID  REFERENCES "blogs" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("blog_id","related_post_id"));;

DROP TABLE IF EXISTS "students" CASCADE;;

CREATE TABLE IF NOT EXISTS "students" ("id" UUID , "user_id" UUID REFERENCES "admins" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "first_name" VARCHAR(255) NOT NULL, "last_name" VARCHAR(255) NOT NULL, "email" VARCHAR(255) NOT NULL UNIQUE, "phone" VARCHAR(255) NOT NULL, "address" VARCHAR(255), "date_of_birth" TIMESTAMP WITH TIME ZONE, "gender" VARCHAR(255), "nationality" VARCHAR(255), "passport_number" VARCHAR(255), "education" JSONB NOT NULL, "english_test" JSONB, "preferred_countries" JSONB NOT NULL, "preferred_courses" JSONB NOT NULL, "status" VARCHAR(255) NOT NULL DEFAULT 'prospect', "source" VARCHAR(255) NOT NULL DEFAULT 'website', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "students_status" ON "students" ("status");

CREATE INDEX IF NOT EXISTS "students_created_at" ON "students" ("created_at");

DROP TABLE IF EXISTS "courses" CASCADE;;

CREATE TABLE IF NOT EXISTS "courses" ("id" UUID , "name" VARCHAR(255) NOT NULL, "slug" VARCHAR(255) UNIQUE, "category" VARCHAR(255), "description" TEXT NOT NULL DEFAULT '', "duration" VARCHAR(255), "degree_level" VARCHAR(255) NOT NULL, "countries" JSONB NOT NULL, "tuition_range" VARCHAR(255), "application_fee" VARCHAR(255), "is_free_to_apply" BOOLEAN NOT NULL DEFAULT false, "scholarship_available" BOOLEAN NOT NULL DEFAULT false, "intake" VARCHAR(255), "requirements" TEXT, "career_outcomes" TEXT, "is_featured" BOOLEAN NOT NULL DEFAULT false, "is_active" BOOLEAN NOT NULL DEFAULT true, "seo" JSONB NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "courses_category" ON "courses" ("category");

CREATE INDEX IF NOT EXISTS "courses_degree_level" ON "courses" ("degree_level");

CREATE INDEX IF NOT EXISTS "courses_is_featured" ON "courses" ("is_featured");

CREATE INDEX IF NOT EXISTS "courses_slug" ON "courses" ("slug");

DROP TABLE IF EXISTS "course_universities" CASCADE;;

CREATE TABLE IF NOT EXISTS "course_universities" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "course_id" UUID  REFERENCES "courses" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "university_id" UUID  REFERENCES "universities" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("course_id","university_id"));;

DROP TABLE IF EXISTS "destinations" CASCADE;;

CREATE TABLE IF NOT EXISTS "destinations" ("id" UUID , "name" VARCHAR(255) NOT NULL UNIQUE, "slug" VARCHAR(255) UNIQUE, "code" VARCHAR(255), "flag" VARCHAR(255), "description" TEXT NOT NULL DEFAULT '', "short_description" VARCHAR(300), "image" VARCHAR(255) NOT NULL DEFAULT '', "cover_image" VARCHAR(255) NOT NULL DEFAULT '', "why_study_here" JSONB NOT NULL, "popular_universities" JSONB NOT NULL, "popular_courses" JSONB NOT NULL, "tuition_info" TEXT, "cost_of_living" TEXT, "scholarships" TEXT, "english_requirements" TEXT, "visa_info" TEXT, "work_opportunities" TEXT, "intakes" TEXT, "application_process" TEXT, "faqs" JSONB NOT NULL, "seo" JSONB NOT NULL, "is_featured" BOOLEAN NOT NULL DEFAULT false, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "destinations_is_featured" ON "destinations" ("is_featured");

CREATE INDEX IF NOT EXISTS "destinations_slug" ON "destinations" ("slug");

CREATE INDEX IF NOT EXISTS "destinations_created_at" ON "destinations" ("created_at");

DROP TABLE IF EXISTS "destination_related_blogs" CASCADE;;

CREATE TABLE IF NOT EXISTS "destination_related_blogs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "destination_id" UUID  REFERENCES "destinations" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "blog_id" UUID  REFERENCES "blogs" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("destination_id","blog_id"));;

DROP TABLE IF EXISTS "scholarships" CASCADE;;

CREATE TABLE IF NOT EXISTS "scholarships" ("id" UUID , "name" VARCHAR(255) NOT NULL, "slug" VARCHAR(255) UNIQUE, "university_id" UUID REFERENCES "universities" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "country" VARCHAR(255) NOT NULL, "description" TEXT NOT NULL DEFAULT '', "eligibility" TEXT, "amount" VARCHAR(255), "type" VARCHAR(255) NOT NULL DEFAULT 'merit', "deadline" TIMESTAMP WITH TIME ZONE, "application_process" TEXT, "requirements" JSONB NOT NULL, "link" VARCHAR(255), "is_featured" BOOLEAN NOT NULL DEFAULT false, "is_active" BOOLEAN NOT NULL DEFAULT true, "seo" JSONB NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "scholarships_country" ON "scholarships" ("country");

CREATE INDEX IF NOT EXISTS "scholarships_type" ON "scholarships" ("type");

CREATE INDEX IF NOT EXISTS "scholarships_is_featured" ON "scholarships" ("is_featured");

DROP TABLE IF EXISTS "applications" CASCADE;;

CREATE TABLE IF NOT EXISTS "applications" ("id" UUID , "student_id" UUID NOT NULL REFERENCES "students" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, "university_id" UUID NOT NULL REFERENCES "universities" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, "course" VARCHAR(255) NOT NULL, "intake" VARCHAR(255) NOT NULL, "year" INTEGER NOT NULL, "status" VARCHAR(255) NOT NULL DEFAULT 'draft', "documents" JSONB NOT NULL, "offer_letter" VARCHAR(255), "notes" TEXT, "deadlines" JSONB NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "applications_student_id_status" ON "applications" ("student_id", "status");

CREATE INDEX IF NOT EXISTS "applications_university_id" ON "applications" ("university_id");

CREATE INDEX IF NOT EXISTS "applications_created_at" ON "applications" ("created_at");

DROP TABLE IF EXISTS "inquiries" CASCADE;;

CREATE TABLE IF NOT EXISTS "inquiries" ("id" UUID , "full_name" VARCHAR(100) NOT NULL, "phone" VARCHAR(255) NOT NULL, "email" VARCHAR(255), "preferred_country" VARCHAR(255), "highest_education" VARCHAR(255), "interested_course" VARCHAR(255), "preferred_intake" VARCHAR(255), "english_test" VARCHAR(255), "message" TEXT, "source" VARCHAR(255) NOT NULL DEFAULT 'website', "status" VARCHAR(255) NOT NULL DEFAULT 'new', "notes" JSONB NOT NULL, "assigned_counselor_id" UUID REFERENCES "admins" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "inquiries_status" ON "inquiries" ("status");

CREATE INDEX IF NOT EXISTS "inquiries_created_at" ON "inquiries" ("created_at");

DROP TABLE IF EXISTS "media" CASCADE;;

CREATE TABLE IF NOT EXISTS "media" ("id" UUID , "filename" VARCHAR(255) NOT NULL, "original_name" VARCHAR(255) NOT NULL, "url" VARCHAR(255) NOT NULL, "thumbnail_url" VARCHAR(255) NOT NULL DEFAULT '', "mimetype" VARCHAR(255), "size" INTEGER, "folder" VARCHAR(255) NOT NULL DEFAULT 'general', "uploaded_by_id" UUID REFERENCES "admins" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "media_folder" ON "media" ("folder");

DROP TABLE IF EXISTS "contactmessages" CASCADE;;

CREATE TABLE IF NOT EXISTS "contactmessages" ("id" UUID , "name" VARCHAR(255) NOT NULL, "email" VARCHAR(255) NOT NULL, "phone" VARCHAR(255), "subject" VARCHAR(255), "message" TEXT NOT NULL, "is_read" BOOLEAN NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "contactmessages_is_read" ON "contactmessages" ("is_read");

CREATE INDEX IF NOT EXISTS "contactmessages_created_at" ON "contactmessages" ("created_at");

DROP TABLE IF EXISTS "faqs" CASCADE;;

CREATE TABLE IF NOT EXISTS "faqs" ("id" UUID , "question" TEXT NOT NULL, "answer" TEXT NOT NULL, "category" VARCHAR(255) NOT NULL DEFAULT 'general', "order" INTEGER NOT NULL DEFAULT 0, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "faqs_category" ON "faqs" ("category");

CREATE INDEX IF NOT EXISTS "faqs_order" ON "faqs" ("order");

DROP TABLE IF EXISTS "pageseos" CASCADE;;

CREATE TABLE IF NOT EXISTS "pageseos" ("id" UUID , "key" VARCHAR(255) NOT NULL UNIQUE, "label" VARCHAR(255), "path" VARCHAR(255), "seo" JSONB NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

DROP TABLE IF EXISTS "services" CASCADE;;

CREATE TABLE IF NOT EXISTS "services" ("id" UUID , "title" VARCHAR(255) NOT NULL, "slug" VARCHAR(255) UNIQUE, "icon" VARCHAR(255) NOT NULL DEFAULT '', "description" TEXT NOT NULL DEFAULT '', "features" JSONB NOT NULL, "detailed_content" TEXT, "image" VARCHAR(255) NOT NULL DEFAULT '', "order" INTEGER NOT NULL DEFAULT 0, "is_active" BOOLEAN NOT NULL DEFAULT true, "seo" JSONB NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "services_order" ON "services" ("order");

DROP TABLE IF EXISTS "sitesettings" CASCADE;;

CREATE TABLE IF NOT EXISTS "sitesettings" ("id" UUID , "company" JSONB NOT NULL, "contact" JSONB NOT NULL, "social_media" JSONB NOT NULL, "office_hours" VARCHAR(255) NOT NULL DEFAULT 'Sun-Fri: 9:00 AM - 5:00 PM', "statistics" JSONB NOT NULL, "hero_settings" JSONB NOT NULL, "seo" JSONB NOT NULL, "footer_settings" JSONB NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

DROP TABLE IF EXISTS "successstories" CASCADE;;

CREATE TABLE IF NOT EXISTS "successstories" ("id" UUID , "student_name" VARCHAR(255) NOT NULL, "photo" VARCHAR(255) NOT NULL DEFAULT '', "country" VARCHAR(255), "university" VARCHAR(255), "course" VARCHAR(255), "intake" VARCHAR(255), "testimonial" TEXT NOT NULL, "is_featured" BOOLEAN NOT NULL DEFAULT false, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "successstories_is_featured" ON "successstories" ("is_featured");

DROP TABLE IF EXISTS "teammembers" CASCADE;;

CREATE TABLE IF NOT EXISTS "teammembers" ("id" UUID , "name" VARCHAR(255) NOT NULL, "position" VARCHAR(255) NOT NULL, "avatar" VARCHAR(255) NOT NULL DEFAULT '', "bio" TEXT NOT NULL DEFAULT '', "specialization" VARCHAR(255), "email" VARCHAR(255), "phone" VARCHAR(255), "social_links" JSONB NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "teammembers_order" ON "teammembers" ("order");

DROP TABLE IF EXISTS "testimonials" CASCADE;;

CREATE TABLE IF NOT EXISTS "testimonials" ("id" UUID , "student_name" VARCHAR(255) NOT NULL, "country" VARCHAR(255), "university" VARCHAR(255), "course" VARCHAR(255), "quote" TEXT NOT NULL, "rating" INTEGER NOT NULL DEFAULT 5, "image" VARCHAR(255) NOT NULL DEFAULT '', "is_featured" BOOLEAN NOT NULL DEFAULT false, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE INDEX IF NOT EXISTS "testimonials_is_featured" ON "testimonials" ("is_featured");
